# Generated by Django 2.2.1 on 2019-06-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askor', '0002_auto_20190605_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, max_length=10, null=True),
        ),
    ]
