# Generated by Django 2.2.1 on 2019-06-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askor', '0003_auto_20190606_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_info_ru',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='add_info_uk',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
