# Generated by Django 2.2.1 on 2019-06-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askor', '0006_auto_20190606_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock_ru',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock_uk',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(blank=True, default=None, max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_uk',
            field=models.CharField(blank=True, default=None, max_length=130, null=True),
        ),
    ]
