# Generated by Django 2.2.1 on 2019-06-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askor', '0004_auto_20190607_0101'),
        ('askor', '0007_auto_20190606_1701'),
    ]

    operations = [
    ]
