# Generated by Django 2.2.1 on 2019-06-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askor', '0008_merge_20190607_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description_uk',
        ),
    ]
