# Generated by Django 2.2.1 on 2019-06-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askor', '0009_auto_20190607_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clicks',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
