# Generated by Django 2.2.1 on 2019-06-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askor', '0010_product_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default=None, upload_to='static/media/categories_images/'),
        ),
    ]
