# Generated by Django 2.2.1 on 2019-07-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askor', '0014_auto_20190702_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default=0, upload_to='categories_images/'),
            preserve_default=False,
        ),
    ]
