# Generated by Django 2.2.1 on 2019-07-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askor', '0015_auto_20190703_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_table',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='askor.ProductCategory'),
            preserve_default=False,
        ),
    ]
