# Generated by Django 2.2.1 on 2019-07-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askor', '0016_auto_20190704_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articul',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
