# Generated by Django 2.2.1 on 2019-07-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askor', '0017_product_articul'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='application_area',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='coating',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='diameter',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='material',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='standart',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
