# Generated by Django 2.2.1 on 2019-07-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askor', '0018_auto_20190705_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='application_area_ru',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='application_area_uk',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='coating_ru',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='coating_uk',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='material_ru',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='material_uk',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
